ejercicio1: ej1.pml
	spin -v -u100 ej1.pml

ejercicio2: ej2.pml
	spin -p -l ej2.pml #spin -v -u100 ej2.pml

ejercicio3: ej3.pml
	spin -m -a ej3.pml #spin -v -u100 ej3.pml
	gcc -o pan pan.c
	./pan
	rm pan.*

    
